"""empty message

Revision ID: 08fe07fa48e5
Revises: df90d0295e13
Create Date: 2023-06-07 01:02:46.425302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fe07fa48e5'
down_revision = 'df90d0295e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_areas', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_areas', 'capacity')
    # ### end Alembic commands ###
