"""empty message

Revision ID: 0bd41f68f360
Revises: bd5ed5f52686
Create Date: 2023-06-08 10:39:07.314266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd41f68f360'
down_revision = 'bd5ed5f52686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_areas', sa.Column('detection_method', sa.String(), nullable=True))
    op.add_column('parking_areas', sa.Column('video_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_areas', 'video_path')
    op.drop_column('parking_areas', 'detection_method')
    # ### end Alembic commands ###
