"""empty message

Revision ID: 5ebaffb35922
Revises: 75fe318e277c
Create Date: 2023-06-07 21:55:54.831179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebaffb35922'
down_revision = '75fe318e277c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('reservation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'reservation_time')
    # ### end Alembic commands ###
