"""empty message

Revision ID: 75fe318e277c
Revises: c922f244fe47
Create Date: 2023-06-07 21:54:30.701916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fe318e277c'
down_revision = 'c922f244fe47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('reservation_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'reservation_time')
    # ### end Alembic commands ###
