"""empty message

Revision ID: 844ba639b43e
Revises: 52e819af26f2
Create Date: 2023-06-07 22:09:19.219964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844ba639b43e'
down_revision = '52e819af26f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('reservation_datetime', sa.DateTime(), nullable=True))
    op.drop_column('reservations', 'reservation_date')
    op.drop_column('reservations', 'reservation_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('reservation_time', sa.DATETIME(), nullable=False))
    op.add_column('reservations', sa.Column('reservation_date', sa.DATE(), nullable=False))
    op.drop_column('reservations', 'reservation_datetime')
    # ### end Alembic commands ###
