"""empty message

Revision ID: bd5ed5f52686
Revises: f1097a305717
Create Date: 2023-06-08 10:32:11.057606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5ed5f52686'
down_revision = 'f1097a305717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_areas', sa.Column('map_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_areas', 'map_link')
    # ### end Alembic commands ###
