"""empty message

Revision ID: c922f244fe47
Revises: 08fe07fa48e5
Create Date: 2023-06-07 21:51:37.949397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c922f244fe47'
down_revision = '08fe07fa48e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('reservation_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'reservation_time')
    # ### end Alembic commands ###
