"""empty message

Revision ID: f1097a305717
Revises: 844ba639b43e
Create Date: 2023-06-07 22:29:37.321071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1097a305717'
down_revision = '844ba639b43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'active')
    # ### end Alembic commands ###
